/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgamal;

import java.util.ArrayList;
import java.util.Base64;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author buida
 */
public class GUI_ELGAMAL extends java.awt.Frame {

    public ArrayList<Integer> arr_ban_ma;
    int max = 39367, min = 255;
    int k;

    /**
     * Creates new form GUI_ELGAMAL
     */
    public GUI_ELGAMAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_receive = new javax.swing.JButton();
        txt_p2 = new javax.swing.JTextField();
        txt_beta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_p1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_decrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_banro2 = new javax.swing.JTextArea();
        btn_clear = new javax.swing.JButton();
        btn_generation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_banro1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_banma2 = new javax.swing.JTextArea();
        btn_encrypt = new javax.swing.JButton();
        txt_alpha = new javax.swing.JTextField();
        txt_a = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_banma1 = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(880, 440));
        setTitle("Gui_ELGAMAL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_receive.setText("Receive Ciphertext");
        btn_receive.setName("btn_receive"); // NOI18N
        btn_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiveActionPerformed(evt);
            }
        });
        add(btn_receive, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        txt_p2.setEditable(false);
        txt_p2.setName("txt_p2"); // NOI18N
        add(txt_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 80, 20));

        txt_beta.setEditable(false);
        txt_beta.setName("txt_beta"); // NOI18N
        add(txt_beta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, 20));

        jLabel2.setText("Alpha");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 20));

        txt_p1.setEditable(false);
        txt_p1.setName("txt_p1"); // NOI18N
        add(txt_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 80, 20));

        jLabel3.setText("P");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 20));

        jLabel4.setText("Beta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        btn_decrypt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_decrypt.setText("Decrypt");
        btn_decrypt.setName("btn_decrypt"); // NOI18N
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });
        add(btn_decrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 100, 40));

        txt_banro2.setEditable(false);
        txt_banro2.setColumns(20);
        txt_banro2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banro2.setLineWrap(true);
        txt_banro2.setRows(5);
        txt_banro2.setName("txt_banro2"); // NOI18N
        jScrollPane1.setViewportView(txt_banro2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 310, 100));

        btn_clear.setText("Clear");
        btn_clear.setName("btn_clear"); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        btn_generation.setText("Generation Key");
        btn_generation.setName("btn_generation"); // NOI18N
        btn_generation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generationActionPerformed(evt);
            }
        });
        add(btn_generation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        txt_banro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banro1.setLineWrap(true);
        txt_banro1.setRows(5);
        txt_banro1.setName("txt_banro1"); // NOI18N
        jScrollPane3.setViewportView(txt_banro1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 310, 100));

        txt_banma2.setColumns(20);
        txt_banma2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banma2.setLineWrap(true);
        txt_banma2.setRows(5);
        txt_banma2.setName("txt_banma2"); // NOI18N
        jScrollPane4.setViewportView(txt_banma2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 310, 100));

        btn_encrypt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_encrypt.setText("Encrypt");
        btn_encrypt.setName("btn_encrypt"); // NOI18N
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });
        add(btn_encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 40));

        txt_alpha.setEditable(false);
        txt_alpha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_alpha.setName("txt_alpha"); // NOI18N
        add(txt_alpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, 20));

        txt_a.setEditable(false);
        txt_a.setName("txt_a"); // NOI18N
        add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 80, 20));

        jLabel5.setText("P");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 20));

        jLabel6.setText("a");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 20));

        txt_banma1.setEditable(false);
        txt_banma1.setColumns(20);
        txt_banma1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banma1.setLineWrap(true);
        txt_banma1.setRows(5);
        txt_banma1.setName("txt_banma1"); // NOI18N
        jScrollPane5.setViewportView(txt_banma1);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    //check so nguyen to
    public boolean CheckSNT(int n) {
        // so nguyen n < 2 khong phai la so nguyen to
        if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    private void btn_generationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generationActionPerformed
        // TODO add your handling code here:
        
        int p, a, alpha, beta;
        Random genaration = new Random();
        do {
            p = genaration.nextInt((max)) + min;
        } while (CheckSNT(p) == false ); // hoac p<= 2 || p <= 2

        txt_p1.setText("" + p);
        txt_p2.setText("" + p);
        //set a
        a = genaration.nextInt((p - 2) -2) + 2;
        txt_a.setText("" + a);
        //set alpha
        alpha = genaration.nextInt((p - 1) - 1) + 1;
        txt_alpha.setText("" + alpha);
        //set beta
        beta = BinhPhuongNhan(alpha, a, p);
        txt_beta.setText("" + beta);

        k = genaration.nextInt((p - 2)) +1;
        System.out.println("k " +k);

    }//GEN-LAST:event_btn_generationActionPerformed

    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed
        try{
            if(txt_p1.getText().length() ==0 ||
                    txt_alpha.getText().length() ==0 ||
                    txt_beta.getText().length() ==0 ||
                    txt_a.getText().length() ==0){
                JOptionPane.showMessageDialog(this,
                "Bạn chưa Genenation key!",
                "Thông báo",
                JOptionPane.OK_OPTION);
                return;
            }
            if(txt_banro1.getText().length() == 0){
                JOptionPane.showMessageDialog(this,
                "Hãy nhập thông tin cần mã hóa trước !",
                "Thông báo",
                JOptionPane.OK_OPTION);
                return;
            }
        arr_ban_ma = new ArrayList<>();
        txt_banma1.setText("");
        txt_banma2.setText("");
        txt_banro2.setText("");
        int p = Integer.valueOf(txt_p1.getText());
        int alpha = Integer.valueOf(txt_alpha.getText());
        int beta = Integer.valueOf(txt_beta.getText());
        //lay ban ro tu text field ban ro
        String ban_ro = txt_banro1.getText();
        int[] ro1 = new int[ban_ro.length()];
        //chuyen ban ro tu string sang mang int
        for (int i = 0; i < ban_ro.length(); i++) {
            ro1[i] = (int) ban_ro.charAt(i);
        }
        int[] ma = new int[ro1.length];
        // ma hoa voi mang int(ban ro)
        for (int i = 0; i < ro1.length; i++) {
            ma[i] = ((ban_ro.charAt(i) * BinhPhuongNhan(beta, k, p)) % p);
        }
        String ban_ma = "";
        // chuyen mang int(ban ma) sang sting
        for (int i = 0; i < ma.length; i++) {
            ban_ma += (char) ma[i];
        }
        // chuyen string ban ma sang byte
        byte[] b1 = ban_ma.getBytes();
        // chuyen byte ban ma sang string dang base64
        String ban_ma1 = Base64.getEncoder().encodeToString(b1);
        //dua ban ma vao text field ban ma 1
        txt_banma1.setText(ban_ma1);
        } 
        catch(Exception e ){
            JOptionPane.showMessageDialog(this,
                "Bạn chưa Genenation key!",
                "Thông báo",
                JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btn_encryptActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:'
        txt_a.setText("");
        txt_alpha.setText("");
        txt_beta.setText("");
        txt_p1.setText("");
        txt_p2.setText("");
        txt_banro1.setText("");
        txt_banro2.setText("");
        txt_banma1.setText("");
        txt_banma2.setText("");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiveActionPerformed
        // TODO add your handling code here:
        if(txt_banma1.getText().length() == 0){
            JOptionPane.showMessageDialog(this,
                "Không có bản mã nào!",
                "Thông báo",
                JOptionPane.OK_OPTION);
                return;
        }
        txt_banma2.setText(txt_banma1.getText());
    }//GEN-LAST:event_btn_receiveActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_banma2.getText().length() == 0){
                JOptionPane.showMessageDialog(this,
                "Không có thông tin cần giải mã!",
                "Thông báo",
                JOptionPane.OK_OPTION);
                return;
            }
        int p = Integer.valueOf(txt_p1.getText());
        int a = Integer.valueOf(txt_a.getText());
        int alpha = Integer.valueOf(txt_alpha.getText());
        
        // lay ban ma tu text field ban ma 2
        String ban_ma = txt_banma2.getText();
        //chuyen ban ma tu String  base 64 -> byte
        byte[] bma1 = Base64.getDecoder().decode(ban_ma);
        // chuyen ban ma dang byte -> String
        String s1 = new String(bma1);
        int[] ma1 = new int[s1.length()];
        //Chuyen ban ma String -> mang int
        for (int i = 0; i < s1.length(); i++) {
            ma1[i] = (int) s1.charAt(i);
        }
        // khoi tao y1
        int so_y1 = BinhPhuongNhan(BinhPhuongNhan(alpha, k, p), p - 1 - a, p);
        
        int[] ma2 = new int[ma1.length];
        // tien hanh giai ma ban ma -> ban ro  dang mang int
        for (int i = 0; i < ma1.length; i++) {
            ma2[i] = (ma1[i] * so_y1) % p;
        }
        String ban_ro = "";
        // chuyen ban ro mang int-> String
        for (int i = 0; i < ma2.length; i++) {
            ban_ro += (char) ma2[i];
        }
        //dua ban ro vao text field ban ro 2
        txt_banro2.setText(ban_ro);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Giải mã thất bại",
                "Thông báo",
                JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btn_decryptActionPerformed

    public int BinhPhuongNhan(int alpha, int a, int p) {
        int ketqua = 1, n = p, x = alpha;
        String k = Integer.toBinaryString(a);//chuyen sang nhi phan
        int i = 0;
        while (i < k.length()) {
            ketqua *= ketqua;
            ketqua %= n;
            if (k.charAt(i) == '1') {
                ketqua *= x;
            }
            ketqua %= n;
            i++;
        }
        return ketqua;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ELGAMAL().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_generation;
    private javax.swing.JButton btn_receive;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_alpha;
    private javax.swing.JTextArea txt_banma1;
    private javax.swing.JTextArea txt_banma2;
    private javax.swing.JTextArea txt_banro1;
    private javax.swing.JTextArea txt_banro2;
    private javax.swing.JTextField txt_beta;
    private javax.swing.JTextField txt_p1;
    private javax.swing.JTextField txt_p2;
    // End of variables declaration//GEN-END:variables
}
